name: Release

on:
  push:
    branches:
      - main
      - beta
      - alpha
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        vscode-version: ['1.102.0', 'stable']
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run check-types

      - name: Compile extension
        run: npm run compile

      - name: Run tests
        run: |
          # Start Xvfb for headless testing
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          npm run test
        env:
          DISPLAY: ':99.0'

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta' || github.ref == 'refs/heads/alpha')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: Install vsce globally
        run: npm install -g @vscode/vsce

      - name: Build extension
        run: npm run package

      - name: Package extension
        run: npm run package:vsix

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx semantic-release
